version: 2
workflows:
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node
    working_directory: ~/repo
    environment:
      # Customize the VM max heap limit
      MVN_OPTS: -Xm3200m
    steps:
      - checkout
      #download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "pom.xml"}}
            #fallback to using the latest cache if no exist match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{checksum "pom.xml"}}
      #run tests and generate code coverage
      - run: mvn verify #integration-test
      # now,configured from pom
      #- store_test_results:
      #    path: target/surfire-reports

      - run:
          name: Send To CodeCov
          command: bash <(curl -s https://codecov.io/bash)